Upgrade kotlin version and ktfmt (#4205)
The latest version of IntelliJ's `ktfmt` plugin defaults to version 0.62 which causes files to be reformatted unexpectedly. Upgrading ktfmt alone 0.62 causes 1120 linting errors to show up because kotlin doesn't seem to recognize a class from it, e.g.:

```
src/test/kotlin/com/terraformation/backend/tracking/scenario/ExpectedObservationResult.kt:LINE_UNDEFINED ktfmt(java.lang.NoClassDefFoundError) Could not initialize class com.facebook.ktfmt.util.CompatibilityUtilsKt (...)
```

Upgrade the kotlin version as well to address this.