Make EnumsTest output more useful (#1783)
When EnumsTest detects that English-name entries are missing from a properties
file, make its assertion failure message include a list of lines that can be
copied into the properties file as a starting point.

The English strings will still require human review, and, if needed, comments
will still need to be written to clarify terminology for translators. But this
should make it slightly less annoying to add missing enums to the strings files.

The assertion failure output will look like

    org.opentest4j.AssertionFailedError: Bundle i18n.Enums is missing values ==> expected: <> but was: 
    <public.GrowthForm.Graminoid=Graminoid
    public.GrowthForm.Liana=Liana
    public.GrowthForm.Lichen=Lichen
    public.GrowthForm.Moss=Moss>